### PR TITLE
Update all tabs

### PR DESCRIPTION
**Pull request by dseifert**
When more than one tab is modified and "Save All" is run, only the
currently active tab got its title updated. Though all documents
were saved, the other tabs still showed the asterisk.

This patch goes through all open tabs and updates their status.

P.S.: It would be nicer if only the actually affected tabs would get updated, though I did not see how to get it limited to those.

### CODE REVIEW

**Comment by trollixx** [comment]
I cannot reproduce the problem. When I have multiple tabs with modified contents, `Save All` command works properly: all tabs lose asterisk marks.

**Comment by dseifert** [comment]
Using QT 5.4.0 with QT Creator 3.3.1 on Ubuntu 14.04 (64 bit), this does not work properly. Also tested on Ubuntu 12.04 with QT 5.4.1 and QT Creator 3.3.1.

Reproduction steps with your current master:
* open two or more tabs
* in tab A, insert a space and remove it (tab is marked as modified)
* in tab B, insert a space and remove it (tab is marked as modified)
* press Ctrl+Shift+S or select "Save All" from the menu -> now tab B is shown as unmodified (no asterisk) but tab A still shows an asterisk

Putting debug output in updateTabText() it seems that this is called more often when multiple tabs are affected, however the code only asks for the current editor from the EditorManager. Shouldn't the "current editor" always be the same as long as the user has not changed anything? I am not a QT developer, it's my first time with QT Creator and also I can't find documentation for the Core::EditorManager::currentEditor() function, but for me it looks like it should only update the current editor/tab.

If it works on your system, maybe it's a difference in platform or QT version?

**Comment by trollixx** [comment]
Please check if 9f338d13cfad2ae6705d3088e0522b215d0b4006 fixes the problem for you.

**Comment by dseifert** [comment]
Yes, this fixes the problem.

**Pull request closed without merging**
