### PR TITLE
Session-Restore

### PR DESCRIPTION
**Pull request by dseifert**
midi-pascal added session restore to the plugin. This pull-request reduces the change to its core (e.g. removed several code formatting changes).

Tested with qt-creator-3.3 on Linux 64 bit.

### CODE REVIEW

**Comment by trollixx** [comment]
Hi,

Thanks for contribution. There are several issues with this pull request.

1. I am not sure, that I can merge third-party code, without their consent.
2. Multiple commits should be squashed.
3. No merge commits.

And the plugin already compiles with Qt Creator 3.3.0, so I don't get why the first change is needed. Looks like it's based on older code, than the current master.

**Comment by dseifert** [comment]
These are valid points, but tricky to do.

1. This depends entirely on the license of the code. Generally he forked (via intermediary) via you, so this should be okay. On that note, I am not sure it is okay (at least looking at it from the outside) that you put the code under the LGPL and claim the copyright (at the very least there are other contributors, also you forked it from SNA Soft which released their  code under a Creative Commons Attribution License according to http://sourceforge.net/projects/tabbededitor), unless they gave you permission to change this to LGPL or you basically rewrote the software from scratch.

2. Squashing should not be done for pushed changes to an external repository. And these commits are not mine, but actually from two other developers. How should I squash this? This would make me the author of their code.

3. and your other comment: my goal is to have one version of the plugin with all the features I want. I could just make my own fork and merge everything in, but I don't have the time nor QT knowledge right now to maintain this. Your fork looks the best, and the restoreSession feature is a nice one. As this has been done by @midi-pascal, courtesy is to merge it in - which in this case brings in some superfluous commits like QtCreator 3.3.0 compatibility. I kind of agree with the merge commit issue, but the solution would be to merge his branch, and then add a commit undoing his coding-style convention changes. Unfortunately he did not do a small feature commit and a large cleanup commit, so cherry-picking is out of the question, too. And either way, if the coding conventions conflict, you have to merge it.

Please advise.

**Comment by trollixx** [comment]
I've asked SNA Soft to clarify the licence of his code. I didn't check SourceForge page in the past. The original code [says](https://github.com/trollixx/qtcreator-tabbededitor-plugin/blob/5a9b72dbc15b4857cfe639f1e69222751ce1612e/TabbedEditor.pluginspec.in#L4), that it's available under the same licence as Qt Creator.

**Comment by dseifert** [comment]
Perfect. So this should cover your point 1 above. However with your recent changes the pull request does not merge cleanly anymore. Please let me know how to continue. Do you agree that having a session restore would be a nice feature?

**Comment by trollixx** [comment]
I shall implement a proper session handling depending on `SessionManager`.

**Comment by trollixx** [comment]
I've added a support for sessions in b98722775417c213c48aac9071add63c71470d05. I don't use sessions and tabs much, so please create reports for any issues you'd discover.

**Comment by dseifert** [comment]
Thank you!!

**Comment by midi-pascal** [comment]
Thanks to both of you!

**Pull request closed without merging**
